name: AstroStackerPro
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: '17.0'
targets:
  AstroStackerPro:
    type: application
    platform: iOS
    sources:
      - path: Sources
    resources:
      - Assets
      - Docs
      - UI_Preview
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.AstroStackerPro
