name: AstroStackerPro
options:
  bundleIdPrefix: com.stemonti
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: en
packages:
  SwiftAA:
    url: https://github.com/onekiloparsec/SwiftAA.git
    from: 2.0.0
settings:
  base:
    SWIFT_VERSION: 5.9

targets:
  AstroStackerPro:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: AstroStackerPro/Sources
      - path: AstroStackerPro/Assets
        buildPhase: resources
      - path: AstroStackerPro/Models
        buildPhase: resources
      - path: AstroStackerPro/Metal
      - path: Docs
        optional: true
        buildPhase: resources
    dependencies:
      - package: SwiftAA
  AstroStackerProTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: AstroStackerPro
    info:
      path: AstroStackerPro/Info.plist
      properties:
        CFBundleName: AstroStackerPro
        CFBundleIdentifier: com.stemonti.AstroStackerPro
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSCameraUsageDescription: "Serve per scattare foto al cielo notturno."
        NSPhotoLibraryAddUsageDescription: "Serve per salvare le immagini elaborate."
schemes:
  - name: AstroStackerPro
    build:
      targets:
        AstroStackerPro: all
        AstroStackerProTests: [test]
